name: NotificaciÃ³n a ntfy

on:
  push:
    branches:
      - main

jobs:
  enviar-notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensaje a ntfy
        run: |
          curl -X POST \
          -H "Title: Nuevo Push en main ðŸš€" \
          -H "Priority: 4" \
          -d "Se subiÃ³ nuevo cÃ³digo al repositorio." \
          https://ntfy.sh/devops-itla
